### PR TITLE
Add AR and gamepads module of WebXR spec

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes https://github.com/immersive-web/webxr-gamepads-module/issues/10

cc @NellWaliczek @ddorwin @toji

r? @tidoust

### CODE REVIEW

**Comment by tidoust** [comment]
Thanks! I just moved the URLs around to keep the A-Z sort.

**Comment by Manishearth** [comment]
@tidoust what do I need to do for these IDLs to start appearing in WPT?

**Comment by tidoust** [comment]
Adding the specs to the crawl triggered the creation of:
https://github.com/web-platform-tests/wpt/pull/19033
https://github.com/web-platform-tests/wpt/pull/19034
... but what happens there is out of my league. Ping @foolip

**Comment by foolip** [comment]
@lukebjerring took care of it :)
https://github.com/web-platform-tests/wpt/pull/19169
https://github.com/web-platform-tests/wpt/pull/19170

**Pull request merged**
